#define COMMAND_POS 'p'
#define COMMAND_VEL 'v'
#define READ_ENCODER 'e'
#define READ_VEL_ENCODER 'a'
#define HOME 'h'
#define SET_VEL_MODE 's'
#define UNSET_VEL_MODE 'u'
#define SEND_SLAVE 'r'
#define CLEAR_JOINTS 'c'
#define SET_HOTEND_TEMPERATURE 't'
#define SET_EXTRUDER 'n'
#define TEMP_STATUS 'i'

#define PRINT_STATE 'e'